CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Models/AlekseyAntonov/Multiplication.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TestWcfSite.Models.AlekseyAntonov
{
    public static class Multiplication
    {
        public static int X { get; set; }
        public static int Y { get; set; }

        public static int MultExpr()
        {
            return X * Y;
        }

        public static int MultExpr(int x, int y)
        {
            return x * y;
        }
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Models/SergeyDerkoModels/User11.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TestWcfSite.Models.SergeyDerkoModels
{
    public class User11
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }

        public override string ToString()
        {
            return $"{nameof(Name)}: {Name}, {nameof(Surname)}: {Surname}, {nameof(Patronymic)}: {Patronymic}";
        }
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Controllers/SergeyDerkoController.cs
using System.Globalization;
using System.Text;
using System.Web.Mvc;
using TestWcfCommon;
using TestWcfSite.Models.SergeyDerkoModels;

namespace TestWcfSite.Controllers
{
    public class SergeyDerkoController : Controller
    {
        
        // GET: SergeyDerko
        public ActionResult Index()
        {
            Logger.Enter("SergeyDerkoController-->Index()");
            return View();
        }

        public ActionResult InfoSiteLog()
        {
            Logger.Enter("SergeyDerkoController-->InfoLogInSite()");
            var model = new ReadLogInSite();
            ViewBag.InfologInSite = model.Read().Replace("#", "<br />");

            return View();
        }

        public ActionResult InfoLog()
        {
            Logger.Enter("SergeyDerkoController-->InfoLog()");
            var model = new ReadLogModel();
            ViewBag.Infologer = model.AddClass().Replace("#", "<br />");
            return View();
        }


        public ActionResult ScanPcResult()
        {
            Logger.Enter("SergeyDerkoController-->scanPcResult()");
            var scanPc = new ScanPcModel();
            ViewBag.Hdd = scanPc.Hdd;
            ViewBag.Cpu = scanPc.Cpu;
            ViewBag.Video = scanPc.Video;
            ViewBag.Memory = scanPc.Memory;
            return View();
        }

        public ActionResult User_11(User11 user11)
        {
            Logger.Enter("SergeyDerkoController-->Uder_11()");
            var user = new StringBuilder();
            user.Append("Привет тебе - " + user11.Name);
            user.Append(" " + user11.Surname);
            user.Append(" " + user11.Patronymic + "!");
            ViewBag.User = user;
            ViewBag.name = user11.Name;
            return View();
        }
        [HttpPost] // метод принимающий данные с клиента
        public ActionResult Index(CalcModel model, string math)
        {
            Logger.Enter("SergeyDerkoController-->Index()[HttpPost]-->Calc");
            model.Action = math;
            ViewBag.Math = model.Action;
            ViewBag.First = model.First;
            ViewBag.Second = model.Second;
            ViewBag.res = model.Result();
            Logger.Info("первое значение: "+model.First.ToString(CultureInfo.InvariantCulture));
            Logger.Info("выбранное действие: " + model.Action);
            Logger.Info("второе значение: " + model.Second.ToString(CultureInfo.InvariantCulture));
            Logger.Info("результат действия: " + model.Result());
            return View();
        }
        private string TableBuilder()
        {
            Logger.Enter("SergeyDerkoController-->TableBuilder()");
            var str = new StringBuilder();

            for (int i = 2; i < 11; i++)
            {
                str.Append($"{2} x {i} = {2 * i}<br/>");
            }
            return str.ToString();

        }

        public ActionResult Table()
        {
            Logger.Enter("SergeyDerkoController-->Table()");
            ViewBag.table = TableBuilder();

            return View();
        }
        private string TableBuilderOll()
        {
            Logger.Enter("SergeyDerkoController-->TableBuilderOll()");
            var str = new StringBuilder();

            for (int i = 2; i < 11; i++)
            {
                str.Append($"{ViewBag.A} x {i} = {ViewBag.A * i}<br/>");
            }
            return str.ToString();
        }

        public ActionResult TableOll(int? a)
        {
            Logger.Enter("SergeyDerkoController-->TableOll()");
            ViewBag.A = a;
            ViewBag.tableOll = TableBuilderOll();
            return View();
        }

        public ActionResult MultiplicationTable()
        {
            Logger.Enter("SergeyDerkoController-->MultiplicationTable()");
            var exp = new Expression11();
            ViewBag.MTable = exp.MultiplicationTable();
            return View();
        }
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/SergeyDerko/Index.cshtml
@model TestWcfSite.Models.SergeyDerkoModels.CalcModel

<!DOCTYPE html>

<html>
<head>
    <link href="../../Content/SergeyDerko.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>

        <br />

        <a href="SergeyDerko/ScanPcResult" class="button9">Получение данных о компьютере >></a>     <a href="SergeyDerko/MultiplicationTable" class="button9">Таблица умножения >></a>   <a href="SergeyDerko/User_11" class="button9">Ввод данных Пользователя >></a>
        <br />
        <h5>*****************************************************************************************************************************************</h5>
        <a href="SergeyDerko/InfoLog" class="button9">Данные из Логов Службы >></a>  <a href="SergeyDerko/InfoSiteLog" class="button9">Данные из Логов Сайта >></a>
        <h3>Простенький калькулятор</h3>
        @using (Html.BeginForm("Index", "SergeyDerko"))
        {
            @Html.TextBoxFor(a => a.First)

            <select name="math">
                <option>действие</option>
                <option>+</option>
                <option>-</option>
                <option>*</option>
                <option>/</option>
            </select>

            @Html.TextBoxFor(b => b.Second)
            <input id="Submit" type="submit" value="=" />
            if (ViewBag.res != null)
            {
                <strong> @ViewBag.res</strong>
            }
        }
        <h3>Результат действий  @ViewBag.First @ViewBag.Math @ViewBag.Second = @ViewBag.res</h3>
    </div>
</body>
</html>

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/SergeyDerko/InfoLog.cshtml
@model TestWcfSite.Models.SergeyDerkoModels.ReadLogModel

@{
    ViewBag.Title = "InfoLog";
}

<h2>InfoLog</h2>
@Html.Raw(ViewBag.Infologer)

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/SergeyDerko/InfoSiteLog.cshtml
@model TestWcfSite.Models.SergeyDerkoModels.ReadLogInSite

@{
    ViewBag.Title = "InfoSiteLog";
}

<h2>InfoSiteLog</h2>
@Html.Raw(ViewBag.InfologInSite)

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/SergeyDerko/MultiplicationTable.cshtml
@{
    ViewBag.Title = "MultiplicationTable";
}
<link href="../../Content/SergeyDerko.css" rel="stylesheet">
<h2>MultiplicationTable</h2>

<br />
@Html.ActionLink("Таблица умножения на - 2", "Table", "SergeyDerko")
<br />
@Html.ActionLink("Таблица умножения на - что угодно, параметр задается в строке :)", "TableOll", "SergeyDerko", new { a = 3 }, null)
<br />
<div id="box" align="left">
    <table border="2">
        @for (int j = 0, index = 0; j < 10; j++)
        {
            <tr>
                <td>
                    @{
                        var str = ((List<string>)ViewBag.MTable)[index];
                        @Html.Raw(str)
                        index++;
                    }
                </td>
            </tr>
                        }
    </table>

    <table border="2">
        @for (int j = 0, index = 10; j < 10; j++)
        {
            <tr>
                <td>
                    @{
                        var str = ((List<string>)ViewBag.MTable)[index];
                        @Html.Raw(str)
                        index++;
                    }
                </td>
            </tr>
                        }
    </table>
    <table border="2">
        @for (int j = 0, index = 20; j < 10; j++)
        {
            <tr>
                <td>
                    @{
                        var str = ((List<string>)ViewBag.MTable)[index];
                        @Html.Raw(str)
                        index++;
                    }
                </td>
            </tr>
                        }
    </table>

    <table border="2">
        @for (int j = 0, index = 30; j < 10; j++)
        {
            <tr>
                <td>
                    @{
                        var str = ((List<string>)ViewBag.MTable)[index];
                        @Html.Raw(str)
                        index++;
                    }
                </td>
            </tr>
                        }
    </table>

    <table border="2">
        @for (int j = 0, index = 40; j < 10; j++)
        {
            <tr>
                <td>
                    @{
                        var str = ((List<string>)ViewBag.MTable)[index];
                        @Html.Raw(str)
                        index++;
                    }
                </td>
            </tr>
                        }
    </table>

    <table border="2">
        @for (int j = 0, index = 50; j < 10; j++)
        {
            <tr>
                <td>
                    @{
                        var str = ((List<string>)ViewBag.MTable)[index];
                        @Html.Raw(str)
                        index++;
                    }
                </td>
            </tr>
                        }
    </table>
    <table border="2">
        @for (int j = 0, index = 60; j < 10; j++)
        {
            <tr>
                <td>
                    @{
                        var str = ((List<string>)ViewBag.MTable)[index];
                        @Html.Raw(str)
                        index++;
                    }
                </td>
            </tr>
                        }
    </table>

    <table border="2">
        @for (int j = 0, index = 70; j < 10; j++)
        {
            <tr>
                <td>
                    @{
                        var str = ((List<string>)ViewBag.MTable)[index];
                        @Html.Raw(str)
                        index++;
                    }
                </td>
            </tr>
                        }
    </table>
</div>

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/SergeyDerko/ScanPcResult.cshtml
@model TestWcfSite.Models.SergeyDerkoModels.ScanPcModel

<!DOCTYPE html>
<html>
<head>

</head>
<body>
    <h2>Получение данных о компьютере из службы</h2>
    <div>
        <table border="1">
            <tr>
                <td>
                    <strong>Информация о накопителях</strong>
                    <br />
                    @Html.Raw(ViewBag.Hdd)
                </td>
            </tr>
            <tr>
                <td>
                    <strong>Информация о процессоре</strong>
                    <br />
                    @Html.Raw(ViewBag.Cpu)
                </td>
            </tr>
            <tr>
                <td>
                    <strong>Информация о видеокарте</strong>
                    <br />
                    @Html.Raw(ViewBag.Video)
                </td>
            </tr>
            <tr>
                <td>
                    <strong>Информация о оперативной памяти</strong>
                    <br />
                    @Html.Raw(ViewBag.Memory)
                </td>
            </tr>
        </table>
    </div>

</body>
</html>

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/SergeyDerko/TableOll.cshtml
@{
    ViewBag.Title = "TableOll";
}
<br />
<table border="2">
    <tr>
        <td>
            @Html.Raw(ViewBag.tableOll)
        </td>
    </tr>
</table>

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/SergeyDerko/User_11.cshtml
@model TestWcfSite.Models.SergeyDerkoModels.User11

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Строка ввода пользователя</title>
</head>
<body>
    <div>

        <br />

        @using (Html.BeginForm("User_11", "SergeyDerko"))
        {
            <h3>Введите Ваше имя</h3>
            @Html.TextBoxFor(w => w.Name)
            <h3>Введите Вашу фамилию</h3>

            @Html.TextBoxFor(e => e.Surname)
            <h3>Введите Ваше очество</h3>

            @Html.TextBoxFor(r => r.Patronymic)
            <br />
            <input id="Sub" type="submit" value="Отправить данные" />
            <br />
            <br />
            if (ViewBag.name != null)
            {
                <h2>@ViewBag.User</h2>
            }
        }
    </div>
</body>
</html>