CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Models/DanilaModels/ExpressionD.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TestWcfSite.Models.DanilaModels
{
    public static class ExpressionD
    {
        public static int A { get; set; }
        public static int B { get; set; }
       
        public static int Result()
        {
            return 2 * 2;
        }
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Models/DanilaModels/Map.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TestWcfSite.Models.DanilaModels
{
    public class Map
    {
    public int Id { get; set; }
        public string PlaceName { get; set; } // название места
        public double Traffic { get; set; } // пассажиропоток
        public string Line { get; set; } // линия метро
        public double GeoLong { get; set; } // долгота - для карт google
        public double GeoLat { get; set; } // широта - для карт google
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Models/DanilaModels/Plitka.cs
using PlitkaClientLib.PlitkaServiceReference;

namespace TestWcfSite.Models.DanilaModels
{
    public  class Plitka
    {
        public Plitka()
        {var client =new PlitkaClient();
            client.Close();
            
        }
        public double heightWall { get; set; }
        public double widthWall { get; set; }
        public double heightTile { get; set; }
        public double widthTile { get; set; }

        public double Result()
        {
            string res = "";
            {
                double sqrWall;
                sqrWall = (heightWall * widthWall);
                double sqrTile;
                sqrTile = (heightTile * widthTile);
                double result;
                result = (sqrWall / sqrTile);
                {

                    return result;
                }
            }
        }
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Controllers/DanilaController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using TestWcfSite.Models.DanilaModels;



namespace TestWcfSite.Controllers
{
    public class DanilaController : Controller
    {
        // GET: Danila
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ExpressionD()
        {
            Models.DanilaModels.ExpressionD.B = 2;
            Models.DanilaModels.ExpressionD.A = 2;
            return View();
        }

        public ActionResult Plitka()
        {
            return View();
        }

        [HttpPost] // метод принимающий данные с клиента
        public ActionResult Plitka(Plitka model)
        {

            ViewBag.heightTile = model.heightTile;
            ViewBag.heightWall = model.heightWall;
            ViewBag.widthWall = model.widthWall;
            ViewBag.heightTile = model.heightTile;
            ViewBag.widthTile = model.widthTile;

            ViewBag.res = model.Result();
            return View();
        }

        public ActionResult Map()
        {
            return View();
        }

        
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Danila/ExpressionD.cshtml
@using TestWcfSite.Models.DanilaModels


<h2>Один пример</h2>
@ExpressionD.A
x
@ExpressionD.B
=
@ExpressionD.Result()
<br />

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Danila/Index.cshtml
<div class="col-xs-3">
    <h3>Plitka</h3>
    <p>
        @Html.ActionLink("Перейти", "Plitka","", new { @class = "btn btn-default" })
    </p>
</div>
<div class="col-xs-3">
    <h3>Map</h3>
    <p>
        @Html.ActionLink("Перейти", "Map","", new { @class = "btn btn-default" })
    </p>
</div>

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Danila/Map.cshtml
   
 <script src="https://maps.googleapis.com/maps/api/js?sensor=false&amp;language=ru&amp;key=AIzaSyD2acvoiJX1dCViw5_A29V2J9l3X0Qcky8"
        type="text/javascript"></script>

<style>
    #map_canvas img {
        max-width: none;
    }
</style>

<style>
    .infoDiv {
        height: 200px;
        width: 300px;
        -webkit-user-select: none;
        background-color: white;
    }
</style>
<br />
<div id="map_canvas" style="height: 550px;"></div>

@section scripts {
    <section class="scripts">

        <script type="text/javascript">

    $(document).ready(function () {
        Initialize();
    });

    function Initialize() {

        google.maps.visualRefresh = true;
        var Academy = new google.maps.LatLng(50.398527, 30.516223);

        var mapOptions = {
            zoom: 16,
            center: Academy,
            mapTypeId: google.maps.MapTypeId.G_NORMAL_MAP
        };

        var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);

        var data = [
                  { "Id": 1, "PlaceName": "BrainAcademy", "GeoLong": "50.398527", "GeoLat": "30.516223" },
                 ];

        $.each(data, function (i, item) {
            var marker = new google.maps.Marker({
                'position': new google.maps.LatLng(item.GeoLong, item.GeoLat),
                'map': map,
                'title': item.PlaceName
            });

            marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png')

            var infowindow = new google.maps.InfoWindow({
                content: "<div class='infoDiv'><h2>" + item.PlaceName + "</div></div>"
            });

            google.maps.event.addListener(marker, 'click', function () {
                infowindow.open(map, marker);
            });

        })
    }


        </script>
    </section>
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Danila/Plitka.cshtml
@model TestWcfSite.Models.DanilaModels.Plitka
@{
    ViewBag.Title = "Plitka";
}
@using (Html.BeginForm("Plitka", "Danila", FormMethod.Post))
{


            <p><h2>Размер стены</h2></p>
            <p><h3> @Html.TextBoxFor(a => a.heightWall) X @Html.TextBoxFor(b => b.widthWall)  </h3>
          </p>
        <p><h2>Размер плитки</h2></p>
        <p><h3>  @Html.TextBoxFor(с => с.heightTile) X @Html.TextBoxFor(d => d.widthTile)</h3></p>
        <p>
            <input id="Submit" type="submit" value="calculate" />
        </p>}
            <h2>Вам необходимо   @ViewBag.res плитки</h2>

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Danila/TestDanil.cshtml
@{
    ViewBag.Title = "TestDanil";
}

<h2>TestDanil</h2>