CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Models/Yuriy/Expression.cs
namespace TestWcfSite.Models.Yuriy
{
    public class Expression
    {
        public int A { get; set; }
        public int B { get; set; }
        public Operation Operation { get; set; }

        public int Result()
        {
            return A*B;
        }
    }

    public enum Operation
    {
        Mult = 3
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Models/Yuriymodels/Client.cs
namespace TestWcfSite.Models.Yuriymodels
{
    public class Client
    {
        public string Name { get; set; }
        public string Lastname { get; set; }
        public int Age { get; set; }
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Models/Yuriymodels/CurrencyRate.cs
using System.Collections.Generic;
using CurrencyRateClientLibrary.CurrencyRateServiceReference;

namespace TestWcfSite.Models.Yuriymodels
{
    public class CurrencyRate
    {
        public List<Currency> Current { get; private set; }

        public CurrencyRate()
        {
            var client = new CurrencyRateClient();
            Current = new List<Currency>(client.CurrentRate());

            client.Close();
        }
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Models/Yuriymodels/ExchangeRates.cs
using System;
using System.Configuration;
using System.ServiceModel;
using ExchangeRatesClientLibrary.ExchangeRatesServiceReference;

namespace TestWcfSite.Models.Yuriymodels
{
    public class ExchangeRates
    {
        public ExchangeRates()
        {
            try
            {
                var client = new ExchangeRatesClient();
                CurrentExchange = client.CurrentExchangeRates();
                client.Close();
            }
            catch (EndpointNotFoundException)
            {
                CurrentExchange = "Сервис Exchange Rates не запущен! :(";
            }
        }

        public string CurrentExchange { get; private set; }
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Models/Yuriymodels/Expression.cs
using System.Collections.Generic;

namespace TestWcfSite.Models.Yuriymodels
{
    public class Expression
    {
        public int A { get; set; }
        public int B { get; set; }

        public int Result()
        {
            return A*B;
        }
        
        public static List<Expression> AllTableExpressions()
        {
            var table = new List<Expression>();
            for (var i = 2; i < 10; i++)
            {
                for (var j = 1; j <= 10; j++)
                {
                    table.Add(new Expression {A = i, B = j});
                }
            }
            return table;
        }
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Controllers/YuriyController.cs
using System.Web.Mvc;
using TestWcfSite.Models.Yuriymodels;

namespace TestWcfSite.Controllers
{
    public class YuriyController : Controller
    {
        // GET: Yuriy
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TableMultiply()
        {
            var expression = new Expression {A = 2, B = 2};
            ViewBag.Expression = expression;

            var table = Expression.AllTableExpressions();

            return View(table);
        }

        public ActionResult Client()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Client(Client client)
        {
            var newClient = new Client {Name = client.Name, Lastname = client.Lastname, Age = client.Age};

            return PartialView("_Clientdata", newClient);
        }

        public ActionResult ExchangeRates()
        {
            var currentRates = new ExchangeRates();
            ViewBag.CurrentRates = currentRates.CurrentExchange;
            return View();
        }
        public ActionResult CurrencyRate()
        {
            var now = new CurrencyRate();
            
            return View(now.Current);
        }
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Yuriy/Client.cshtml
@model TestWcfSite.Models.Yuriymodels.Client
@{
    ViewBag.Title = "Client";
}
@using (Html.BeginForm())
{
    <fieldset>
        <legend>Add new client</legend>
        <label>Name:</label>@Html.TextBoxFor(name => name.Name)
        <label>Lastname:</label>@Html.TextBoxFor(lastname => lastname.Lastname)
        <label>Age:</label>@Html.TextBoxFor(age => age.Age)
        <input type="submit" value="Submit"/>
    </fieldset>
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Yuriy/CurrencyRate.cshtml
@model List<CurrencyRateClientLibrary.CurrencyRateServiceReference.Currency>

@{
    ViewBag.Title = "CurrencyRate";
    var grid = new WebGrid(Model);
}

<h2>Currency Rate today - @DateTime.Now.ToShortDateString()</h2>
@grid.GetHtml(tableStyle: "table table-condensed table-striped",
              columns:grid.Columns(
                  grid.Column(columnName: "Id", header: "#"),
                  grid.Column(columnName: "CurrencyName", header: "Валюта", canSort: false),
                  grid.Column(columnName: "CurrencyDescription", header: "Описание", canSort:false),
                  grid.Column(columnName: "Purchase", header: "Покупка"),
                  grid.Column(columnName: "Sale", header: "Продажа")
                  ))

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Yuriy/ExchangeRates.cshtml
@{
    ViewBag.Title = "ExchangeRates";
}

<h2>ExchangeRates</h2>

<span>@ViewBag.CurrentRates</span>

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Yuriy/Index.cshtml
@{
    ViewBag.Title = "Yuriy homepage";
}
<div class="row"> 
    <div class="col-xs-4">
        <h3>Table Multiply</h3>
        <p>Вывод таблицы умножения с помощью частичного представления - <code>Html.Partial</code>.</p>
        <p>
            @Html.ActionLink("Go", "TableMultiply", "Yuriy", new {@class = "btn btn-default"})
        </p>
    </div>
    <div class="col-xs-4">
        <h3>Add new client</h3>
        <p>Отправка данных пользователя через форму и метод <code>post</code>.</p>
        <p>
            @Html.ActionLink("Go", "Client", "Yuriy", new {@class = "btn btn-default"})
        </p>
    </div>
    <div class="col-xs-3">
        <h3>Exchange Rates</h3>
        <p>Вывод <code>string</code> значения полученного с WCF сервиса.</p>
        <p>
            @Html.ActionLink("Go", "ExchangeRates", "Yuriy", new {@class = "btn btn-default"})
        </p>
    </div>
    <div class="col-xs-4">
        <h3>Currency Rate</h3>
        <p>Вывод колекции <code>List<></code> с помощью <code>WebGrid()</code>.</p>
        <p>
            @Html.ActionLink("Go", "CurrencyRate", "Yuriy", new { @class = "btn btn-default"})
        </p>
    </div>
</div>

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Yuriy/TableMultiply.cshtml
@using TestWcfSite.Models.Yuriymodels
@{
    ViewBag.Title = "TableMultiply";
}
<h2>Table Multiply</h2>
<div>
    <h4>Expression</h4>
    @Html.Partial("_Expression", (Expression) ViewBag.Expression)
    @Html.Partial("_Table")
    
</div>

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Yuriy/_Clientdata.cshtml
@model TestWcfSite.Models.Yuriymodels.Client
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3>A new user is added!</h3>
<table class="table table-bordered table-condensed" style="width: 50%" >
    <tr class="active">
        <th>Name</th>
        <th>Lastname</th>
        <th>Age</th>
    </tr>
    <tr>
        <td>@Model.Name</td>
        <td>@Model.Lastname</td>
        <td>@Model.Age</td>
    </tr>
</table>
<br>
@Html.ActionLink("Add again...", "Client", "Yuriy")

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Yuriy/_Expression.cshtml
@model TestWcfSite.Models.Yuriymodels.Expression
@{
    var str = Model.A + " x " + Model.B + " = " + Model.Result();
    <span>@str</span>
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Yuriy/_Table.cshtml
@model IEnumerable<TestWcfSite.Models.Yuriymodels.Expression>
@{
    <h4>One Table</h4>
    var onetable = Model.Where(n => n.A == 2);
    foreach (var exp in onetable)
    {
        @Html.Partial("_Expression", exp)
        <br/>
    }

    <h4>All Tables</h4>
    <table class="table table-condensed" style="width: 75%">
        <tr>
            @for (var i = 2; i <= 5; i++)
            {
                <td>
                    @{
                        var result = Model.Where(n => n.A == i);
                        foreach (var exp in result)
                        {
                            @Html.Partial("_Expression", exp)
                            <br/>
                        }
                    }
                </td>
            }
        </tr>
        <tr>
            @for (var i = 6; i <= 9; i++)
            {
                <td>
                    @{
                        var result = Model.Where(n => n.A == i);
                        foreach (var exp in result)
                        {
                            @Html.Partial("_Expression", exp)
                            <br/>
                        }
                    }
                </td>
            }
        </tr>
    </table>
}