CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Models/AnastasiaNepomiluyev/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TestWcfSite.Models.AnastasiaNepomiluyev
{
    public class User
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }

        public User()
        {
        }

        public User(string firstName, string lastName, int age)
        {
            FirstName = firstName;
            LastName = lastName;
            Age = age;
        }
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Models/KhlopovOlegModel/MeteoTemp.cs
using MeteoTempClientLib.MeteoTempServiceReference;

namespace TestWcfSite.Models.KhlopovOlegModel
{
    public class MeteoTemp
    {
        public MeteoTemp()
        {
            var client = new MeteoTempClient();
            CurrentMeteo = client.CurrentMeteoTemp();
            client.Close();
        }
        public string CurrentMeteo { get; private set; }
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Models/KhlopovOlegModel/User.cs
namespace TestWcfSite.Models.KhlopovOlegModel
{
    public class User
    {
        public string name { get; set; }
        public int age { get; set; }
        public string sex { get; set; }

        public string Result()
        {
            var res = "Добрый день: " + name + " ваш возраст: " + age + " и пол: " + sex;
            return res;
        }
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Models/PikhotaSerhiiModels/User.cs
namespace TestWcfSite.Models.PikhotaSerhiiModels
{
    public class User
    {
        public string Surname { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }

        public User()
        {
            
        }

        public User(string surname, string name, int age)
        {
            Surname = surname;
            Name = name;
            Age = age;
        }
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Controllers/OlegController.cs
using System.Collections.Generic;
using System.Text;
using System.Web.Mvc;
using TestWcfSite.Models.KhlopovOlegModel;
using System.Linq;
using System.Xml.Linq;

namespace TestWcfSite.Controllers
{
    public class Base
    {
        public List<string> TabList;
    }

    public class InList
    {
        string messg;

        public string mesInList(int val, int var, int fin)
        {
            messg =  val + " * " + var + " = " + fin + " |\n";
            return messg;
        }
    }

    public class Mult : Base
    {
        public int x;
        public int y;
        public int z;

        public Mult(int InX, int InY)
        {
            TabList = new List<string>();
            for (x = InX; x <= InY; x++)
            {
                for (y = InX; y <= InY; y++)
                {
                    z = x * y;
                    InList Adder = new InList();
                    TabList.Add(Adder.mesInList(x, y, z));
                }
            }
        }
    }

    public class OlegController : Controller
    {
        // GET: Oleg
        public ActionResult Index()
        {
            return View();
        }

        public string MultResult()
        {
            var str = new StringBuilder();
            Mult Start = new Mult(1, 10);
            foreach (var i in Start.TabList)
            {
                str.Append(i);
            };
            /*Base newBase = new Base();
            foreach (var alya in TabList)
            {
                ViewBag.First = alya;
            }*/
            return str.ToString();
        }

        public ActionResult Table()
        {
            ViewBag.table = MultResult();

            return View();
        }

        public ActionResult User(User model)
        {
            ViewBag.name = model.name;
            ViewBag.age = model.age;
            ViewBag.sex = model.sex;

            ViewBag.result = model.Result();

            return View();
        }
        /*
        public ActionResult MultResult()
        {
            for (int i = 1, m; i <= 10; i++)
            {
                for (int j = 1; j <= 10; j++)
                {
                    m = i*j;
                    mess newWord = new mess(i, j, m);
                    newWord.GO();
                    RowInts.Add(newWord);
                    m = 0;                    
                }
            }
            ViewBag.Mess = RowInts;
            return View();
        }
    }

    public class mess
    {
        public int first;
        public int second;
        public int third;
        public string newM;

        public mess(int a, int b, int c)
        {
            first = a;
            second = b;
            third = c;
        }

        internal void GO()
        {
            newM = first + " * " + second + " = " + third;
        }*/

        public ActionResult MeteoTemp()
        {
            var currentTemp = new MeteoTemp();
            ViewBag.CurrentTemp = currentTemp.CurrentMeteo;
            return View();
        }
    }
}

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Oleg/Index.cshtml
@{
    ViewBag.Title = "Oleg homepage";
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
</body>
</html>
<div class="row">
    <div class="col-xs-4">
        <h3>Table Multiply</h3>
        <p>Вывод таблицы умножения</p>
        <p>
            @Html.ActionLink(" Таблица умножения ", "Table", "Oleg", new { @class = "btn btn-default" })
        </p>
    </div>
    <div class="col-xs-4">
        <h3>User</h3>
        <p>Вывод пользователя</p>
        <p>
            @Html.ActionLink(" User ", "User", "Oleg", new { @class = "btn btn-default" })
        </p>
    </div>
    <div class="col-xs-4">
        <h3>Weather in Kyiv</h3>
        <p>Температуры</p>
        <p>
            @Html.ActionLink(" MeteoTemp ", "MeteoTemp", "Oleg", new { @class = "btn btn-default" })
        </p>
    </div>
</div>

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Oleg/MeteoTemp.cshtml
@{
    ViewBag.Title = "Temperature in Kyiv";
}

<h2>MeteoTemp</h2>

<span>
    @Html.Raw(ViewBag.CurrentTemp)
</span>

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Oleg/Table.cshtml
@{
    ViewBag.Title = "Table";
}
<h2>Table</h2>
<table border="2">
    <tr>
        <td>
            @Html.Raw(ViewBag.table)
        </td>
    </tr>
</table>

CW/02Module/202/TestWcf/Client/TestWcfSite/TestWcfSite/Views/Oleg/User.cshtml
@model TestWcfSite.Models.KhlopovOlegModel.User
@{
    ViewBag.Title = "User";
}
<h2>User</h2>

@using (Html.BeginForm("User", "Oleg", FormMethod.Post))
{
    <th>
        @Html.Label("name:")<br />
        @Html.TextBoxFor(x => x.name)<br />
        @Html.Label("age:")<br />
        @Html.TextBoxFor(y => y.age)<br />
        @Html.Label("sex")<br />
        @Html.TextBoxFor(z => z.sex)<br />
    </th>
    <th><input type="submit" value="Update" style="width: 100%; height: 100%" /></th>
    <br />
    <br />
    @Html.Raw(ViewBag.result)
}